version: "3.7"
services:
  app:
    build:
      args:
        user: pedido
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: pedido
    container_name: pedido-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - pedido

  db:
    image: mysql:5.7
    container_name: pedido-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: homestead
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_PASSWORD: secret
      MYSQL_USER: homestead
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    networks:
      - pedido

  nginx:
    image: nginx:1.17-alpine
    container_name: pedido-nginx
    restart: unless-stopped
    ports:
      - 8000:80
    volumes:
      - ./:/var/www
      - ./docker-compose/nginx:/etc/nginx/conf.d
    networks:
      - pedido
  
  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 8082:80
    environment:
      - PMA_ARBITRARY=1
      - MEMORY_LIMIT=1G
      - UPLOAD_LIMIT=1G
    networks:
      - pedido

networks:
  pedido:
    driver: bridge
